# Generated by Django 5.0.4 on 2024-04-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('nebulosa', 'nebulosa'), ('estrela', 'estrela'), ('galaxia', 'galaxia'), ('planeta', 'planeta')], default='', max_length=100),
        ),
    ]
